k * f

In [16]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 3], stride=1)




# Apply the convolution operation
output = conv2d(sample_tensor)


# Print the result
print(output)


tensor([[[[-0.2019],
          [-0.2019],
          [-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466],
          [-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636],
          [ 0.2636],
          [ 0.2636]]],


        [[[-0.2019],
          [-0.2019],
          [-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466],
          [-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636],
          [ 0.2636],
          [ 0.2636]]]], grad_fn=<ConvolutionBackward0>)


In [17]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=2)

output2 = maxpool(output)

print(output2)

tensor([[[[-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636]]],


        [[[-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [18]:
# output2.shape

torch.Size([2, 3, 2, 1])

In [19]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

print(output3)

tensor([[[[ 0.4077]],

         [[ 0.3020]],

         [[ 0.2059]],

         [[ 0.0535]],

         [[-0.3177]],

         [[ 0.4963]]],


        [[[ 0.4077]],

         [[ 0.3020]],

         [[ 0.2059]],

         [[ 0.0535]],

         [[-0.3177]],

         [[ 0.4963]]]], grad_fn=<ConvolutionBackward0>)


In [21]:
output3.squeeze(-1).squeeze(-1)

tensor([[ 0.4077,  0.3020,  0.2059,  0.0535, -0.3177,  0.4963],
        [ 0.4077,  0.3020,  0.2059,  0.0535, -0.3177,  0.4963]],
       grad_fn=<SqueezeBackward1>)

In [22]:
linear = nn.Linear(6, 6)

In [23]:
linear(output3.squeeze(-1).squeeze(-1))

tensor([[0.4312, 0.1090, 0.0821, 0.2245, 0.1628, 0.0890],
        [0.4312, 0.1090, 0.0821, 0.2245, 0.1628, 0.0890]],
       grad_fn=<AddmmBackward0>)

1 * f

In [42]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output = conv2d(sample_tensor)


# Print the result
print(output)

tensor([[[[-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953]],

         [[ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285]],

         [[ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603]]],


        [[[-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953]],

         [[ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285]],

         [[ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603]]]], grad_fn=<ConvolutionBackward0>)


In [44]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=[2, 1])

output2 = maxpool(output)

print(output2)

tensor([[[[-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953]],

         [[ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285]],

         [[ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603]]],


        [[[-0.2701, -0.2827, -0.2953],
          [-0.2701, -0.2827, -0.2953]],

         [[ 0.0574,  0.0144, -0.0285],
          [ 0.0574,  0.0144, -0.0285]],

         [[ 0.2419,  0.2511,  0.2603],
          [ 0.2419,  0.2511,  0.2603]]]],
       grad_fn=<MaxPool2DWithIndicesBackward0>)


In [45]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

print(output3)

tensor([[[[ 0.3801,  0.3779,  0.3757]],

         [[-0.2949, -0.2924, -0.2900]],

         [[-0.1774, -0.1755, -0.1736]],

         [[ 0.2811,  0.2837,  0.2863]],

         [[ 0.0463,  0.0316,  0.0168]],

         [[-0.2090, -0.2092, -0.2094]]],


        [[[ 0.3801,  0.3779,  0.3757]],

         [[-0.2949, -0.2924, -0.2900]],

         [[-0.1774, -0.1755, -0.1736]],

         [[ 0.2811,  0.2837,  0.2863]],

         [[ 0.0463,  0.0316,  0.0168]],

         [[-0.2090, -0.2092, -0.2094]]]], grad_fn=<ConvolutionBackward0>)


In [63]:
output3.squeeze(2).squeeze().view(2, -1)

tensor([[ 0.3801,  0.3779,  0.3757, -0.2949, -0.2924, -0.2900, -0.1774, -0.1755,
         -0.1736,  0.2811,  0.2837,  0.2863,  0.0463,  0.0316,  0.0168, -0.2090,
         -0.2092, -0.2094],
        [ 0.3801,  0.3779,  0.3757, -0.2949, -0.2924, -0.2900, -0.1774, -0.1755,
         -0.1736,  0.2811,  0.2837,  0.2863,  0.0463,  0.0316,  0.0168, -0.2090,
         -0.2092, -0.2094]], grad_fn=<ViewBackward0>)

In [62]:
# output3.squeeze(2).shape

torch.Size([2, 6, 3])

In [64]:
linear = nn.Linear(18, 18)

In [65]:
linear(output3.squeeze(2).squeeze().view(2, -1))

tensor([[-0.1639, -0.1184,  0.0149,  0.2797, -0.3745, -0.2559, -0.4160,  0.0438,
         -0.0841,  0.1180, -0.0045, -0.1350,  0.0167,  0.2969,  0.2432,  0.2967,
         -0.3890, -0.2443],
        [-0.1639, -0.1184,  0.0149,  0.2797, -0.3745, -0.2559, -0.4160,  0.0438,
         -0.0841,  0.1180, -0.0045, -0.1350,  0.0167,  0.2969,  0.2432,  0.2967,
         -0.3890, -0.2443]], grad_fn=<AddmmBackward0>)

indiv 1*f

In [92]:
sample_tensor.shape

torch.Size([2, 1, 5, 3])

In [93]:
sample_tensor

tensor([[[[0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000]]],


        [[[0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000],
          [0.1000, 0.2000, 0.3000]]]])

In [94]:
sample_tensor[:, :, :, 1].unsqueeze(-1)

tensor([[[[0.2000],
          [0.2000],
          [0.2000],
          [0.2000],
          [0.2000]]],


        [[[0.2000],
          [0.2000],
          [0.2000],
          [0.2000],
          [0.2000]]]])

In [105]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output1 = conv2d(sample_tensor[:, :, :, 0].unsqueeze(-1))
output2 = conv2d(sample_tensor[:, :, :, 1].unsqueeze(-1))
output3 = conv2d(sample_tensor[:, :, :, 2].unsqueeze(-1))

# Concatenate the outputs
output = torch.cat([output1, output2, output3], dim=-1)

# Print the result
print(output)

tensor([[[[-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011]],

         [[-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206]],

         [[ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135]]],


        [[[-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011]],

         [[-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206]],

         [[ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135]]]], grad_fn=<CatBackward0>)


In [106]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=[2, 1])

output2 = maxpool(output)

print(output2)

tensor([[[[-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011]],

         [[-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206]],

         [[ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135]]],


        [[[-0.3191, -0.3601, -0.4011],
          [-0.3191, -0.3601, -0.4011]],

         [[-0.5450, -0.6328, -0.7206],
          [-0.5450, -0.6328, -0.7206]],

         [[ 0.0039,  0.0087,  0.0135],
          [ 0.0039,  0.0087,  0.0135]]]],
       grad_fn=<MaxPool2DWithIndicesBackward0>)


In [107]:
output2[:, :, :, 1].unsqueeze(-1)

tensor([[[[-0.3601],
          [-0.3601]],

         [[-0.6328],
          [-0.6328]],

         [[ 0.0087],
          [ 0.0087]]],


        [[[-0.3601],
          [-0.3601]],

         [[-0.6328],
          [-0.6328]],

         [[ 0.0087],
          [ 0.0087]]]], grad_fn=<UnsqueezeBackward0>)

In [108]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output2_1 = conv2d_2(output2[:, :, :, 0].unsqueeze(-1))
output2_2 = conv2d_2(output2[:, :, :, 1].unsqueeze(-1))
output2_3 = conv2d_2(output2[:, :, :, 2].unsqueeze(-1))

# Concatenate the outputs
output3 = torch.cat([output2_1, output2_2, output2_3], dim= -1)

print(output3)

tensor([[[[ 0.0466,  0.0069, -0.0327]],

         [[ 0.0372,  0.0707,  0.1043]],

         [[ 0.4431,  0.4589,  0.4747]],

         [[-0.1993, -0.1784, -0.1575]],

         [[ 0.1335,  0.1062,  0.0790]],

         [[ 0.0921,  0.0695,  0.0470]]],


        [[[ 0.0466,  0.0069, -0.0327]],

         [[ 0.0372,  0.0707,  0.1043]],

         [[ 0.4431,  0.4589,  0.4747]],

         [[-0.1993, -0.1784, -0.1575]],

         [[ 0.1335,  0.1062,  0.0790]],

         [[ 0.0921,  0.0695,  0.0470]]]], grad_fn=<CatBackward0>)


In [109]:
output3.squeeze(2).squeeze().view(2, -1)

tensor([[ 0.0466,  0.0069, -0.0327,  0.0372,  0.0707,  0.1043,  0.4431,  0.4589,
          0.4747, -0.1993, -0.1784, -0.1575,  0.1335,  0.1062,  0.0790,  0.0921,
          0.0695,  0.0470],
        [ 0.0466,  0.0069, -0.0327,  0.0372,  0.0707,  0.1043,  0.4431,  0.4589,
          0.4747, -0.1993, -0.1784, -0.1575,  0.1335,  0.1062,  0.0790,  0.0921,
          0.0695,  0.0470]], grad_fn=<ViewBackward0>)

In [110]:
linear = nn.Linear(18, 18)

In [111]:
linear(output3.squeeze(2).squeeze().view(2, -1))

tensor([[-0.0579, -0.1339, -0.0588, -0.0633, -0.1419, -0.2735,  0.1854,  0.1371,
         -0.2424,  0.0845,  0.2781,  0.1761, -0.0079, -0.0681,  0.1500, -0.2788,
          0.1598, -0.2898],
        [-0.0579, -0.1339, -0.0588, -0.0633, -0.1419, -0.2735,  0.1854,  0.1371,
         -0.2424,  0.0845,  0.2781,  0.1761, -0.0079, -0.0681,  0.1500, -0.2788,
          0.1598, -0.2898]], grad_fn=<AddmmBackward0>)