正常

In [16]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 3], stride=1)




# Apply the convolution operation
output = conv2d(sample_tensor)


# Print the result
print(output)


tensor([[[[-0.2019],
          [-0.2019],
          [-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466],
          [-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636],
          [ 0.2636],
          [ 0.2636]]],


        [[[-0.2019],
          [-0.2019],
          [-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466],
          [-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636],
          [ 0.2636],
          [ 0.2636]]]], grad_fn=<ConvolutionBackward0>)


In [17]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=2)

output2 = maxpool(output)

print(output2)

tensor([[[[-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636]]],


        [[[-0.2019],
          [-0.2019]],

         [[-0.1466],
          [-0.1466]],

         [[ 0.2636],
          [ 0.2636]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [18]:
output2.shape

torch.Size([2, 3, 2, 1])

In [19]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

print(output3)

tensor([[[[ 0.4077]],

         [[ 0.3020]],

         [[ 0.2059]],

         [[ 0.0535]],

         [[-0.3177]],

         [[ 0.4963]]],


        [[[ 0.4077]],

         [[ 0.3020]],

         [[ 0.2059]],

         [[ 0.0535]],

         [[-0.3177]],

         [[ 0.4963]]]], grad_fn=<ConvolutionBackward0>)


In [20]:
flattened = output3.view(-1, output3.size(-2), output3.size(-1)).flatten(start_dim=1)
print(flattened)

tensor([[ 0.4077],
        [ 0.3020],
        [ 0.2059],
        [ 0.0535],
        [-0.3177],
        [ 0.4963],
        [ 0.4077],
        [ 0.3020],
        [ 0.2059],
        [ 0.0535],
        [-0.3177],
        [ 0.4963]], grad_fn=<ReshapeAliasBackward0>)


In [21]:
output3.squeeze(-1).squeeze(-1)

tensor([[ 0.4077,  0.3020,  0.2059,  0.0535, -0.3177,  0.4963],
        [ 0.4077,  0.3020,  0.2059,  0.0535, -0.3177,  0.4963]],
       grad_fn=<SqueezeBackward1>)

In [22]:
linear = nn.Linear(6, 6)

In [23]:
linear(output3.squeeze(-1).squeeze(-1))

tensor([[0.4312, 0.1090, 0.0821, 0.2245, 0.1628, 0.0890],
        [0.4312, 0.1090, 0.0821, 0.2245, 0.1628, 0.0890]],
       grad_fn=<AddmmBackward0>)