k * f

In [114]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 3], stride=1)




# Apply the convolution operation
output = conv2d(sample_tensor)

output = nn.ReLU()(output)

# Print the result
print(output)


tensor([[[[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0628],
          [0.0628],
          [0.0628],
          [0.0628]]],


        [[[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0628],
          [0.0628],
          [0.0628],
          [0.0628]]]], grad_fn=<ReluBackward0>)


In [115]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=2)

output2 = maxpool(output)

print(output2)

tensor([[[[0.0000],
          [0.0000]],

         [[0.0000],
          [0.0000]],

         [[0.0628],
          [0.0628]]],


        [[[0.0000],
          [0.0000]],

         [[0.0000],
          [0.0000]],

         [[0.0628],
          [0.0628]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [116]:
# output2.shape

In [117]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[[0.0000]],

         [[0.2015]],

         [[0.0000]],

         [[0.0000]],

         [[0.1370]],

         [[0.0000]]],


        [[[0.0000]],

         [[0.2015]],

         [[0.0000]],

         [[0.0000]],

         [[0.1370]],

         [[0.0000]]]], grad_fn=<ReluBackward0>)


In [118]:
output3.squeeze(-1).squeeze(-1)

tensor([[0.0000, 0.2015, 0.0000, 0.0000, 0.1370, 0.0000],
        [0.0000, 0.2015, 0.0000, 0.0000, 0.1370, 0.0000]],
       grad_fn=<SqueezeBackward1>)

In [119]:
linear = nn.Linear(6, 6)

In [120]:
linear(output3.squeeze(-1).squeeze(-1))

tensor([[-0.3906,  0.3673, -0.4096, -0.2764, -0.2987,  0.3283],
        [-0.3906,  0.3673, -0.4096, -0.2764, -0.2987,  0.3283]],
       grad_fn=<AddmmBackward0>)

1 * f

In [121]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output = conv2d(sample_tensor)

output = nn.ReLU()(output)

# Print the result
print(output)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)


In [122]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=[2, 1])

output2 = maxpool(output)

print(output2)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [123]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0001, 0.0001]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0001, 0.0001]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)


In [124]:
output3.squeeze(2).squeeze().view(2, -1)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0001, 0.0001, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0001, 0.0001, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<ViewBackward0>)

In [62]:
# output3.squeeze(2).shape

torch.Size([2, 6, 3])

In [125]:
linear = nn.Linear(18, 18)

In [126]:
linear(output3.squeeze(2).squeeze().view(2, -1))

tensor([[ 0.1454, -0.1280,  0.1212,  0.1041, -0.1520,  0.1633, -0.2259,  0.1657,
          0.1884,  0.1912, -0.1242,  0.0899, -0.2008,  0.0369,  0.0685,  0.2056,
         -0.2348,  0.1385],
        [ 0.1454, -0.1280,  0.1212,  0.1041, -0.1520,  0.1633, -0.2259,  0.1657,
          0.1884,  0.1912, -0.1242,  0.0899, -0.2008,  0.0369,  0.0685,  0.2056,
         -0.2348,  0.1385]], grad_fn=<AddmmBackward0>)

indiv 1*f

In [129]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output1 = conv2d(sample_tensor[:, :, :, 0].unsqueeze(-1))
output2 = conv2d(sample_tensor[:, :, :, 1].unsqueeze(-1))
output3 = conv2d(sample_tensor[:, :, :, 2].unsqueeze(-1))

# Concatenate the outputs
output = torch.cat([output1, output2, output3], dim=-1)

output = nn.ReLU()(output)

# Print the result
print(output)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214]]]], grad_fn=<ReluBackward0>)


In [130]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=[2, 1])

output2 = maxpool(output)

print(output2)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.4093, 0.4654, 0.5214],
          [0.4093, 0.4654, 0.5214]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [107]:
output2[:, :, :, 1].unsqueeze(-1)

tensor([[[[-0.3601],
          [-0.3601]],

         [[-0.6328],
          [-0.6328]],

         [[ 0.0087],
          [ 0.0087]]],


        [[[-0.3601],
          [-0.3601]],

         [[-0.6328],
          [-0.6328]],

         [[ 0.0087],
          [ 0.0087]]]], grad_fn=<UnsqueezeBackward0>)

In [131]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output2_1 = conv2d_2(output2[:, :, :, 0].unsqueeze(-1))
output2_2 = conv2d_2(output2[:, :, :, 1].unsqueeze(-1))
output2_3 = conv2d_2(output2[:, :, :, 2].unsqueeze(-1))

# Concatenate the outputs
output3 = torch.cat([output2_1, output2_2, output2_3], dim= -1)

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[[0.3934, 0.3981, 0.4028]],

         [[0.0000, 0.0000, 0.0283]],

         [[0.1054, 0.0966, 0.0878]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]],


        [[[0.3934, 0.3981, 0.4028]],

         [[0.0000, 0.0000, 0.0283]],

         [[0.1054, 0.0966, 0.0878]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)


In [132]:
output3.squeeze(2).squeeze().view(2, -1)

tensor([[0.3934, 0.3981, 0.4028, 0.0000, 0.0000, 0.0283, 0.1054, 0.0966, 0.0878,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3934, 0.3981, 0.4028, 0.0000, 0.0000, 0.0283, 0.1054, 0.0966, 0.0878,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<ViewBackward0>)

In [133]:
linear = nn.Linear(18, 18)

In [134]:
linear(output3.squeeze(2).squeeze().view(2, -1))

tensor([[ 0.2331,  0.0246,  0.1755,  0.0873,  0.0515,  0.2342,  0.2422,  0.1798,
         -0.0835, -0.0174,  0.0634, -0.2209, -0.0689,  0.0290,  0.1012, -0.1497,
         -0.2451,  0.1000],
        [ 0.2331,  0.0246,  0.1755,  0.0873,  0.0515,  0.2342,  0.2422,  0.1798,
         -0.0835, -0.0174,  0.0634, -0.2209, -0.0689,  0.0290,  0.1012, -0.1497,
         -0.2451,  0.1000]], grad_fn=<AddmmBackward0>)