k * f

In [4]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 3], stride=1)




# Apply the convolution operation
output = conv2d(sample_tensor)

output = nn.ReLU()(output)

# Print the result
print(output)


tensor([[[[0.3338],
          [0.3338],
          [0.3338],
          [0.3338]],

         [[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0119],
          [0.0119],
          [0.0119],
          [0.0119]]],


        [[[0.3338],
          [0.3338],
          [0.3338],
          [0.3338]],

         [[0.0000],
          [0.0000],
          [0.0000],
          [0.0000]],

         [[0.0119],
          [0.0119],
          [0.0119],
          [0.0119]]]], grad_fn=<ReluBackward0>)


In [8]:
maxpool = torch.nn.MaxPool2d(kernel_size=[4, 1], stride=2)

output2 = maxpool(output)

print(output2)

tensor([[[[0.3338],
          [0.3338]],

         [[0.0000],
          [0.0000]],

         [[0.0119],
          [0.0119]]],


        [[[0.3338],
          [0.3338]],

         [[0.0000],
          [0.0000]],

         [[0.0119],
          [0.0119]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [116]:
# output2.shape

In [117]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[[0.0000]],

         [[0.2015]],

         [[0.0000]],

         [[0.0000]],

         [[0.1370]],

         [[0.0000]]],


        [[[0.0000]],

         [[0.2015]],

         [[0.0000]],

         [[0.0000]],

         [[0.1370]],

         [[0.0000]]]], grad_fn=<ReluBackward0>)


In [118]:
output3.squeeze(-1).squeeze(-1)

tensor([[0.0000, 0.2015, 0.0000, 0.0000, 0.1370, 0.0000],
        [0.0000, 0.2015, 0.0000, 0.0000, 0.1370, 0.0000]],
       grad_fn=<SqueezeBackward1>)

In [119]:
linear = nn.Linear(6, 6)

In [120]:
linear(output3.squeeze(-1).squeeze(-1))

tensor([[-0.3906,  0.3673, -0.4096, -0.2764, -0.2987,  0.3283],
        [-0.3906,  0.3673, -0.4096, -0.2764, -0.2987,  0.3283]],
       grad_fn=<AddmmBackward0>)

1 * f

In [121]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ],
                [
                [[0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# Define the convolution layer
conv2d = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=[2, 1], stride=1)

# Apply the convolution operation
output = conv2d(sample_tensor)

output = nn.ReLU()(output)

# Print the result
print(output)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)


In [122]:
maxpool = torch.nn.MaxPool2d(kernel_size=[2, 1], stride=[2, 1])

output2 = maxpool(output)

print(output2)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0196, 0.0000, 0.0000],
          [0.0196, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [123]:
conv2d_2 = torch.nn.Conv2d(in_channels=3, out_channels=3*2, kernel_size=[2, 1], stride=1)

output3 = conv2d_2(output2)

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0001, 0.0001]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0001, 0.0001]],

         [[0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)


In [124]:
output3.squeeze(2).squeeze().view(2, -1)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0001, 0.0001, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0001, 0.0001, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<ViewBackward0>)

In [62]:
# output3.squeeze(2).shape

torch.Size([2, 6, 3])

In [125]:
linear = nn.Linear(18, 18)

In [126]:
linear(output3.squeeze(2).squeeze().view(2, -1))

tensor([[ 0.1454, -0.1280,  0.1212,  0.1041, -0.1520,  0.1633, -0.2259,  0.1657,
          0.1884,  0.1912, -0.1242,  0.0899, -0.2008,  0.0369,  0.0685,  0.2056,
         -0.2348,  0.1385],
        [ 0.1454, -0.1280,  0.1212,  0.1041, -0.1520,  0.1633, -0.2259,  0.1657,
          0.1884,  0.1912, -0.1242,  0.0899, -0.2008,  0.0369,  0.0685,  0.2056,
         -0.2348,  0.1385]], grad_fn=<AddmmBackward0>)

indiv 1*f

In [213]:
import numpy as np
import torch
import torch.nn as nn

# Create a sample batch with two images
sample = np.array([[
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]
                ],
                [
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3],
                [0.1, 0.2, 0.3]
                ]])

# Convert the NumPy array to a PyTorch tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32).transpose(1, 2)

print(sample_tensor.shape)
sample_tensor


torch.Size([2, 3, 5])


tensor([[[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]],

        [[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]]])

In [216]:

# Define the convolution layer
conv1d = torch.nn.Conv1d(in_channels=3, out_channels=3*2, kernel_size=3, stride=1, padding='same', padding_mode = 'zeros')

# Apply the convolution operation
output = conv1d(sample_tensor)

output = nn.ReLU()(output)

# Print the result
print(output)

tensor([[[0.1984, 0.1984, 0.2037, 0.3487, 0.3487],
         [0.1571, 0.1571, 0.0598, 0.0936, 0.0936],
         [0.0000, 0.0000, 0.0000, 0.0064, 0.0064],
         [0.0208, 0.0208, 0.0000, 0.0000, 0.0000],
         [0.2138, 0.2138, 0.1785, 0.0278, 0.0278],
         [0.3367, 0.3367, 0.3120, 0.3179, 0.3179]],

        [[0.1984, 0.1984, 0.2037, 0.3487, 0.3487],
         [0.1571, 0.1571, 0.0598, 0.0936, 0.0936],
         [0.0000, 0.0000, 0.0000, 0.0064, 0.0064],
         [0.0208, 0.0208, 0.0000, 0.0000, 0.0000],
         [0.2138, 0.2138, 0.1785, 0.0278, 0.0278],
         [0.3367, 0.3367, 0.3120, 0.3179, 0.3179]]], grad_fn=<ReluBackward0>)


In [199]:
maxpool = torch.nn.MaxPool1d(kernel_size=2, stride=2, padding = 1)

output2 = maxpool(output)

print(output2)

tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0226, 0.0493],
         [0.1391, 0.1046, 0.1685],
         [0.0000, 0.0000, 0.0000],
         [0.0052, 0.0061, 0.0468]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0226, 0.0493],
         [0.1391, 0.1046, 0.1685],
         [0.0000, 0.0000, 0.0000],
         [0.0052, 0.0061, 0.0468]]], grad_fn=<SqueezeBackward1>)


In [200]:
conv1d_2 = torch.nn.Conv1d(in_channels=3*2, out_channels=3*2*2, kernel_size=2, stride=1, padding='same', padding_mode = 'zeros')

output3 = conv1d_2(output2) 

output3 = nn.ReLU()(output3)

print(output3)

tensor([[[0.2291, 0.2184, 0.2407],
         [0.1103, 0.1311, 0.1052],
         [0.0971, 0.0982, 0.1002],
         [0.0376, 0.0442, 0.0190],
         [0.1258, 0.1471, 0.1385],
         [0.1857, 0.1784, 0.1853],
         [0.0000, 0.0000, 0.0104],
         [0.1618, 0.1515, 0.1572],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.1718, 0.1852, 0.1579],
         [0.0000, 0.0000, 0.0000]],

        [[0.2291, 0.2184, 0.2407],
         [0.1103, 0.1311, 0.1052],
         [0.0971, 0.0982, 0.1002],
         [0.0376, 0.0442, 0.0190],
         [0.1258, 0.1471, 0.1385],
         [0.1857, 0.1784, 0.1853],
         [0.0000, 0.0000, 0.0104],
         [0.1618, 0.1515, 0.1572],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.1718, 0.1852, 0.1579],
         [0.0000, 0.0000, 0.0000]]], grad_fn=<ReluBackward0>)


In [201]:
maxpool = torch.nn.MaxPool1d(kernel_size=2, stride=2, padding = 1)

output4 = maxpool(output3)

print(output4)

tensor([[[0.2291, 0.2407],
         [0.1103, 0.1311],
         [0.0971, 0.1002],
         [0.0376, 0.0442],
         [0.1258, 0.1471],
         [0.1857, 0.1853],
         [0.0000, 0.0104],
         [0.1618, 0.1572],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.1718, 0.1852],
         [0.0000, 0.0000]],

        [[0.2291, 0.2407],
         [0.1103, 0.1311],
         [0.0971, 0.1002],
         [0.0376, 0.0442],
         [0.1258, 0.1471],
         [0.1857, 0.1853],
         [0.0000, 0.0104],
         [0.1618, 0.1572],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.1718, 0.1852],
         [0.0000, 0.0000]]], grad_fn=<SqueezeBackward1>)


In [208]:
conv1d_3 = torch.nn.Conv1d(in_channels=3*2*2, out_channels=3*2*4, kernel_size=2, stride=1, padding='same', padding_mode = 'zeros')

output5 = conv1d_3(output4) 

output5 = nn.ReLU()(output5)

print(output5)

tensor([[[0.0000, 0.0000],
         [0.1186, 0.1531],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0152, 0.0186],
         [0.0000, 0.0137],
         [0.0436, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.1179],
         [0.0507, 0.1427],
         [0.2518, 0.1891],
         [0.0553, 0.0169],
         [0.0000, 0.0000],
         [0.1509, 0.1623],
         [0.1290, 0.0254],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.1077, 0.0000],
         [0.0000, 0.0000],
         [0.2082, 0.2086],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.1030, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.1186, 0.1531],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0152, 0.0186],
         [0.0000, 0.0137],
         [0.0436, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.1179],
         [0.0507, 0.1427],
         [0.2518, 0.1891],
         [0.0553, 0.0169],
         [0.0000, 0.0000],

In [209]:
maxpool = torch.nn.MaxPool1d(kernel_size=2, stride=2, padding = 0)

output6 = maxpool(output5)

print(output6)

tensor([[[0.0000],
         [0.1531],
         [0.0000],
         [0.0000],
         [0.0186],
         [0.0137],
         [0.0436],
         [0.0000],
         [0.1179],
         [0.1427],
         [0.2518],
         [0.0553],
         [0.0000],
         [0.1623],
         [0.1290],
         [0.0000],
         [0.0000],
         [0.1077],
         [0.0000],
         [0.2086],
         [0.0000],
         [0.0000],
         [0.1030],
         [0.0000]],

        [[0.0000],
         [0.1531],
         [0.0000],
         [0.0000],
         [0.0186],
         [0.0137],
         [0.0436],
         [0.0000],
         [0.1179],
         [0.1427],
         [0.2518],
         [0.0553],
         [0.0000],
         [0.1623],
         [0.1290],
         [0.0000],
         [0.0000],
         [0.1077],
         [0.0000],
         [0.2086],
         [0.0000],
         [0.0000],
         [0.1030],
         [0.0000]]], grad_fn=<SqueezeBackward1>)


In [210]:
output6.squeeze(-1).view(2, -1)

tensor([[0.0000, 0.1531, 0.0000, 0.0000, 0.0186, 0.0137, 0.0436, 0.0000, 0.1179,
         0.1427, 0.2518, 0.0553, 0.0000, 0.1623, 0.1290, 0.0000, 0.0000, 0.1077,
         0.0000, 0.2086, 0.0000, 0.0000, 0.1030, 0.0000],
        [0.0000, 0.1531, 0.0000, 0.0000, 0.0186, 0.0137, 0.0436, 0.0000, 0.1179,
         0.1427, 0.2518, 0.0553, 0.0000, 0.1623, 0.1290, 0.0000, 0.0000, 0.1077,
         0.0000, 0.2086, 0.0000, 0.0000, 0.1030, 0.0000]],
       grad_fn=<ViewBackward0>)

In [211]:
output6.squeeze(-1).view(2, -1).shape

torch.Size([2, 24])

In [212]:
linear = nn.Linear(36, 36)

In [183]:
linear(output4.squeeze(-1).squeeze().view(2, -1))

tensor([[ 0.1713,  0.0439,  0.1259,  0.0013, -0.0538, -0.1146, -0.0828,  0.1089,
         -0.2011, -0.1726,  0.0279, -0.2020, -0.0418,  0.0662, -0.0854, -0.0454,
         -0.0550,  0.0886, -0.1903,  0.0798,  0.1003,  0.0180,  0.1123,  0.1244,
         -0.2314, -0.0643,  0.1273, -0.1043, -0.0981,  0.0555, -0.2196,  0.0485,
         -0.0225,  0.1852,  0.0741,  0.1179],
        [ 0.1713,  0.0439,  0.1259,  0.0013, -0.0538, -0.1146, -0.0828,  0.1089,
         -0.2011, -0.1726,  0.0279, -0.2020, -0.0418,  0.0662, -0.0854, -0.0454,
         -0.0550,  0.0886, -0.1903,  0.0798,  0.1003,  0.0180,  0.1123,  0.1244,
         -0.2314, -0.0643,  0.1273, -0.1043, -0.0981,  0.0555, -0.2196,  0.0485,
         -0.0225,  0.1852,  0.0741,  0.1179]], grad_fn=<AddmmBackward0>)